#!/bin/sh

# get external IP address
# used for outgoing Internet connections
# see: https://github.com/rsp/scripts/blob/master/externalip.md

case "$1" in
	""|dns) dig +short -t txt o-o.myaddr.l.google.com @ns1.google.com | sed -e s/\"//g;;
	http) curl -s http://whatismyip.akamai.com/ && echo ;;
	# dns) dig +short myip.opendns.com @resolver1.opendns.com ;;	# this doesn't work any more
	https) curl -s https://4.ifcfg.me/ ;;				# this doesn't work any more
	ftp) echo close | ftp 4.ifcfg.me | awk '{print $4; exit}' ;;	# this doesn't work any more
	telnet) nc 4.ifcfg.me 23 | grep IPv4 | cut -d' ' -f4 ;;		# this doesn't work any more
	*) echo Bad argument >&2 && exit 1 ;;
esac
