#!/bin/sh

if [ `id -u` != "0" ] ; then 
  echo "Rerunning $0 with sudo..."
  sudo $0
  exit $?
fi
x=`find /sys/devices/platform/i8042 -name name | xargs grep -Fl TrackPoint | sed 's/\/input\/input[0-9]*\/name$//'`

sensitivity=`cat $x/sensitivity`
VALUE=`zenity --scale --text="Trackpoint sensitivity" --value=$sensitivity --max-value=255`
case $? in
  0)
    echo "Setting sensitivity to $VALUE"
    echo -n $VALUE > $x/sensitivity;;
  1)
    echo "No sensitivity value selected.";;
  -1)
    echo "An unexpected error has occurred.";;
esac

speed=`cat $x/speed`
VALUE=`zenity --scale --text="Trackpoint speed" --value=$speed --max-value=255`
case $? in
  0)
    echo "Setting speed to $VALUE"
    echo -n $VALUE > $x/speed;;
  1)
    echo "No speed value selected.";;
  -1)
    echo "An unexpected error has occurred.";;
esac

drift_time=`cat $x/drift_time`
VALUE=`zenity --scale --text="Trackpoint drift time (in tenths of a second)" --value=$drift_time --max-value=255`
case $? in
  0)
    echo "Setting drift_time to $VALUE"
    echo -n $VALUE > $x/drift_time;;
  1)
    echo "No drift time value selected.";;
  -1)
    echo "An unexpected error has occurred.";;
esac
