#!/bin/sh

if [ `id -u` != "0" ] ; then 
  echo "Rerunning $0 with sudo..."
  sudo $0
  exit $?
fi
x=`find /sys/devices/platform/i8042 -name name | xargs grep -Fl TrackPoint | sed 's/\/input\/input[0-9]*\/name$//'`

sensitivity=`cat $x/sensitivity`
VALUE=`zenity --scale --text="Trackpoint sensitivity" --value=$sensitivity --max-value=255`
case $? in
  0)
    echo "Setting sensitivity to $VALUE"
    echo -n $VALUE > $x/sensitivity;;
  1)
    echo "No sensitivity value selected.";;
  -1)
    echo "An unexpected error has occurred.";;
esac

speed=`cat $x/speed`
VALUE=`zenity --scale --text="Trackpoint speed" --value=$speed --max-value=255`
case $? in
  0)
    echo "Setting speed to $VALUE"
    echo -n $VALUE > $x/speed;;
  1)
    echo "No speed value selected.";;
  -1)
    echo "An unexpected error has occurred.";;
esac

drift_time=`cat $x/drift_time`
VALUE=`zenity --scale --text="Trackpoint drift time (in tenths of a second)" --value=$drift_time --max-value=255`
case $? in
  0)
    echo "Setting drift_time to $VALUE"
    echo -n $VALUE > $x/drift_time;;
  1)
    echo "No drift time value selected.";;
  -1)
    echo "An unexpected error has occurred.";;
esac

# Information on enabling/disabling acceleration here:
# https://www.reddit.com/r/linux_gaming/comments/535ng5/how_to_disable_mouse_acceleration_with_libinput/

id=`xinput list | sed -n -e 's/.*TrackPoint.*id=\([123456789]\+\).*/\1/p'`
if [ -z "$id" ] ; then
  zenity --error --no-wrap --text="Unable to determine TrackPoint device ID using xinput"
  exit 1
fi
set `xinput --list-props $id | sed -n -e 's/.*libinput Accel Profile Enabled (\(.*\)):.*\([01]\),.*\([0-1]\).*/\1 \2 \3/p'`
prop=$1
adaptive=$2
flat=$3
if [ -z "$prop" ] ; then
  zenity --error --no-wrap --text="Unable to determine TrackPoint acceleration profile property using xinput"
  exit 1
fi
echo "Device ID: $id"
echo "Property ID: $prop"
echo "Adaptive: $adaptive"
echo "Flat: $flat"
if zenity --question --text="Enable acceleration?" ; then
  xinput --set-prop $id $prop 1 0
  echo "Enabling acceleration"
else
  xinput --set-prop $id $prop 0 1
  echo "Disabling acceleration"
fi
